config/routes.rb
Rails.application.routes.draw do
  resources :estimates, only: %i[index show]
  resources :estimate_details, only: %i[show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/estimate.rb
class Estimate < ApplicationRecord
  has_closure_tree_root :root_estimate_detail
end

app/models/estimate_detail.rb
class EstimateDetail < ApplicationRecord
  has_closure_tree order: 'order_number', numeric_order: true, dont_order_roots: true

  belongs_to :estimate
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/estimate_details_controller.rb
class EstimateDetailsController < ApplicationController
  def show
    @estimate_detail = EstimateDetail.find(params[:id])
  end
end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
  def index
    @estimates = Estimate.all
  end

  def show
    @estimate = Estimate.find(params[:id])

    redirect_to estimate_detail_path(@estimate.root_estimate_detail.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/estimate_details/show.html.erb
<%= link_to('Back to Estimates', estimates_path())%>

<h1><%= @estimate_detail.estimate.title %></h1>

<table>
  <caption>
    <% @estimate_detail.ancestors.reverse_each do |detail| %>
      <%= link_to(detail.title, estimate_detail_path(detail.id)) %> >
    <% end %>
    <%= @estimate_detail.title %>
  </caption>
  <thead>
    <tr>
      <th>Order nubmer</th>
      <th>Title</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    <% @estimate_detail.children.each do |detail| %>
      <tr>
        <td class="order"><%= detail.order_number %></td>
        <td class="title"><%= detail.leaf? ? detail.title : link_to(detail.title, estimate_detail_path(detail.id)) %></td>
        <td class="price"><%= detail.self_and_descendants.sum("unit_price * amount") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/estimates/index.html.erb
<h1>Estimates</h1>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    <% @estimates.each do |estimate| %>
      <tr>
        <td><%= estimate.id %></td>
        <td class="title"><%= link_to(estimate.title, estimate_path(estimate.id)) %></td>
        <td class="price"><%= estimate.root_estimate_detail.self_and_descendants.sum("unit_price * amount") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestClosureTree</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>